### ISSUE TITLE
Removing one of for PHPUnit tests definition

### ISSUE THREAD

**Issue by peter279k** [ottosmops/settings#1]
There're two ways for defining PHPUnit test methods:
- Using the ` /** @test */` comment annotation.
- Using the test prefix for method name.

I think it should use one of above way to define PHPUnit test methods.

Once this issue is accepted, I will be happy to work on this.

**Comment by ottosmops** [comment]
Is it a problem to use both?

**Comment by peter279k** [comment]
> Is it a problem to use both?

Actually, it's fine to use both approaches about defining PHPUnit test methods.

This issue I create is about consistency and let developers read codes be readable :).

**Comment by ottosmops** [comment]
Then you can change it, thank you.
